branch-defaults:
  main:
    environment: Appbeanstalk2021-env
    group_suffix: null
global:
  application_name: App_beanstalk_2021
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
